[versions]
kotest = "5.6.2"
kotlin = "1.9.0"
mockito = "5.4.0"

[libraries]
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlin-stdlib-jdk8 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotest-junit5-jvm = { module = "io.kotest:kotest-runner-junit5-jvm", version.ref = "kotest" }
kotest-assertions-core-jvm = { module = "io.kotest:kotest-assertions-core-jvm", version.ref = "kotest" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito" }

[bundles]
kotlin-testing = [ "kotest-junit5-jvm", "kotest-assertions-core-jvm", "mockito-core" ]

[plugins]
dokka = "org.jetbrains.dokka:1.8.20"
gitSemVer = "org.danilopianini.git-sensitive-semantic-versioning:1.1.10"
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-qa = "org.danilopianini.gradle-kotlin-qa:0.48.0"
multiJvmTesting = "org.danilopianini.multi-jvm-test-plugin:0.5.4"
publishOnCentral = "org.danilopianini.publish-on-central:5.0.10"
taskTree = "com.dorongold.task-tree:2.1.1"
